spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop
    username: bestuser
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
server:
  servlet:
    context-path: /auth
  port: 8188
jwt:
  secret: EI&!%Ti34NeSmOtRi7666SUDA23232eto43SEcRET@#$%^&%$@Ponyal?uroD
  lifetime: 36000000