spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop
    username: bestuser
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    baseline-on-migrate: true
server:
  servlet:
    context-path: /