server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - Delete
              - Put
            allowedHeaders: "*"

      routes:
        - id: core-service
          uri: http://localhost:8080/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190/
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8188/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth
            - JwtAuthFilter
jwt:
  secret: EI&!%Ti34NeSmOtRi7666SUDA23232eto43SEcRET@#$%^&%$@Ponyal?uroD